steps:
  - id: "Rodando os testes"
    name: "gcr.io/cloud-builders/go"
    env:
      - GOPATH=$PWD
    args:
      - "test"
      - "."

  - id: "Compilando a função soma"
    name: "gcr.io/cloud-builders/go"
    env:
      - GOPATH=$PWD
    args:
      - "build"
      - "-o"
      - "soma"
      - "."

  - id: "Executando a função soma"
    name: "gcr.io/cloud-builders/go"
    env:
      - GOPATH=$PWD
    args:
      - "./soma"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/desafio-ci:latest"
      - "."

images:
  - "gcr.io/$PROJECT_ID/desafio-ci:latest"
