steps:
  - id: "Rodando os testes"
    name: "gcr.io/cloud-builders/go"
    env:
      - GOPATH=/src
    args:
      - "test"
      - "/src"

  - id: "Compilando a função soma"
    name: "gcr.io/cloud-builders/go"
    env:
      - GOPATH=/src
    args:
      - "build"
      - "-o"
      - "soma"
      - "/src"

  - id: "Executando a função soma"
    name: "gcr.io/cloud-builders/go"
    env:
      - GOPATH=/src
    args:
      - "/src/soma"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/desafio-ci:latest"
      - "."

images:
  - "gcr.io/$PROJECT_ID/desafio-ci:latest"
