steps:
  - id: "Rodando os testes"
    name: "gcr.io/cloud-builders/go"
    args:
      - "test"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/desafio-ci:latest"
      - "."

images:
  - "gcr.io/$PROJECT_ID/desafio-ci:latest"
