steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "soma"]
    env: ["GOPATH=."]
  - name: "gcr.io/cloud-builders/go"
    args: ["test", "soma"]
    env: ["GOPATH=."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--tag=gcr.io/$PROJECT_ID/desafio-ci", "."]
images:
  - "gcr.io/$PROJECT_ID/desafio-ci:latest"
